# render.yaml
# This blueprint defines two services that will be deployed from this repository.

services:
  # Service 1: The FastAPI Web Server (Your "Front of House")
  - type: web
    name: socratic-tutor-api
    runtime: docker
    repo: https://github.com/HemanthRaj0C/Socratic-Backend # IMPORTANT: Change this to your repo URL
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free # Or upgrade to "Starter" to prevent sleeping
    healthCheckPath: /
    envVars:
      - fromGroup: socratic-tutor-secrets

  # Service 2: The RQ Background Worker (Your "Back of House")
  - type: worker
    name: socratic-tutor-worker
    runtime: docker
    repo: https://github.com/HemanthRaj0C/Socratic-Backend # IMPORTANT: Change this to your repo URL
    dockerfilePath: ./Dockerfile.worker
    region: singapore
    plan: free
    envVars:
      - fromGroup: socratic-tutor-secrets