# render.yaml (Simplified for a Single "Combined" Service on the Free Tier)

services:
  # We only define one service that does both jobs.
  - type: web
    name: socratic-tutor-combined-api # A new name to avoid conflict
    runtime: docker
    repo: https://github.com/HemanthRaj0C/Socratic-Backend # Use your repo URL
    region: oregon 
    plan: free # This will now work
    
    # Set a health check path so Render knows your app is running
    healthCheckPath: /
    
    # Point to your existing Dockerfile
    dockerfilePath: ./Dockerfile
    
    # Link the environment group with all your secrets
    envVars:
      - fromGroup: socratic-tutor-secrets